version: '3.1'
services:
  kafka-app:
    image: spotify/kafka
    ports:
      - "2181:2181"
      - "9092:9092"
    hostname: kafka
    container_name: kafka
    environment:
      - "ADVERTISED_HOST=kafka"
      - "ADVERTISED_PORT=9092"
      - "AUTO_CREATE_TOPICS=true"
    command: >
      bash -c
      "(sleep 15s &&
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper
      localhost:2181 --replication-factor 1 --partitions 1
      --topic my-kafka-topic &) && (supervisord -n)"
    networks:
      - app-network
  producer:
    build: producer/
    ports:
      - "8080:8080"
    hostname: localhost
    container_name: producer
    networks:
      - app-network
  consumer:
    build: consumer/
    hostname: localhost
    container_name: consumer
    ports:
      - "8181:8181"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge